self-hosted-runner:
  labels:
    - ubicloud-standard-2
    - ubicloud-standard-4
    - ubicloud-standard-8
    - ubicloud-standard-16
    - buildjet-2vcpu-ubuntu-2204
    - buildjet-4vcpu-ubuntu-2204
    - buildjet-8vcpu-ubuntu-2204
