---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  document-start:
    present: false

  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: true
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0

  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0

  comments:
    min-spaces-from-content: 1

  comments-indentation: enable

  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  key-duplicates: enable
  new-line-at-end-of-file: enable

  octal-values:
    forbid-implicit-octal: true

  quoted-strings:
    quote-type: any
    required: false

  trailing-spaces: enable
